# Generated by Django 4.0.3 on 2022-03-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeintervention',
            name='created_at',
            field=models.DateTimeField(verbose_name='Date de creation'),
        ),
    ]
