# Generated by Django 4.0.3 on 2022-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_alter_typeintervention_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepropriete',
            name='created_at',
            field=models.DateTimeField(verbose_name='Date de creation'),
        ),
    ]
