# Generated by Django 4.0.3 on 2022-04-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0006_alter_propriete_type_propriete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdvreporteagent',
            name='rdv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rendez_vous_agent', to='rdv.rendezvous'),
        ),
    ]
