# Generated by Django 4.0.3 on 2022-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0008_alter_rdvreportedate_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Type de bien'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='consignes_particuliere',
            field=models.CharField(max_length=200, null=True, verbose_name='Consignes particulière'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='info_diverses',
            field=models.CharField(max_length=300, null=True, verbose_name='Informations diverses'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='liste_document_recuperer',
            field=models.CharField(max_length=200, null=True, verbose_name='liste de document à recupérer'),
        ),
    ]
