# Generated by Django 4.1.1 on 2022-09-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0011_rendezvous_agent_constat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='agent',
            field=models.IntegerField(null=True, verbose_name='Agent responsable du RDV'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='client',
            field=models.IntegerField(null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Date de modification'),
        ),
    ]
