# Generated by Django 4.1.1 on 2022-09-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0012_alter_rendezvous_agent_alter_rendezvous_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataire',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email du locataire'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='nom',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du locataire'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='prenom',
            field=models.CharField(max_length=100, null=True, verbose_name='prénom du locataire'),
        ),
    ]
