# Generated by Django 4.1.1 on 2022-09-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0013_alter_locataire_email_alter_locataire_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='agent_constat',
            field=models.CharField(max_length=50, null=True, verbose_name='Agent constat'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='ancien_client_id',
            field=models.CharField(max_length=50, null=True, verbose_name='ancien client ID'),
        ),
    ]
