# Generated by Django 4.1.1 on 2022-09-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0014_alter_rendezvous_agent_constat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='ancien_locataire',
            field=models.CharField(max_length=80, null=True, verbose_name='old locatire'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='date_sortie_ancien_locataire',
            field=models.DateTimeField(null=True, verbose_name='Date de creation'),
        ),
    ]
