# Generated by Django 4.1.1 on 2022-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0015_propriete_ancien_locataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='adresse',
            field=models.CharField(max_length=100, null=True, verbose_name='Adresse de la propriété'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='couleur',
            field=models.CharField(default='red', max_length=30, null=True, verbose_name='couleur du RDV'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(default='Attente prise en charge', max_length=30, null=True, verbose_name='Statut du RDV'),
        ),
        migrations.AlterField(
            model_name='typeintervention',
            name='statut',
            field=models.IntegerField(null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='typeintervention',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name="Type d'intervention"),
        ),
    ]
