# Generated by Django 4.1.1 on 2022-10-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0017_rendezvous_audit_planneir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='audit_planneir',
            new_name='audit_planneur',
        ),
    ]
